# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='Cname')),
                ('cost', models.IntegerField(default=0, verbose_name='Cost')),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('minperson', models.IntegerField(default=0, verbose_name='최소인원')),
                ('maxperson', models.IntegerField(default=0, verbose_name='최대인원')),
                ('place', models.CharField(max_length=50, verbose_name='장소')),
                ('details', models.TextField(verbose_name='상세정보')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'ordering': ['cname'],
            },
        ),
        migrations.CreateModel(
            name='Lfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lnumber', models.IntegerField(null=True, verbose_name='대분류번호')),
                ('lname', models.CharField(max_length=50, verbose_name='large field')),
            ],
            options={
                'ordering': ['lname'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, null=True, verbose_name='요일')),
                ('repetition', models.BooleanField(verbose_name='반복여부')),
                ('starttime', models.TimeField(verbose_name='Starttime')),
                ('endtime', models.TimeField(verbose_name='Endtime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='Sfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snumber', models.IntegerField(null=True, verbose_name='소분류번호')),
                ('sname', models.CharField(max_length=50, verbose_name='small field')),
                ('lfield', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lfield')),
            ],
            options={
                'ordering': ['sname'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='sfield',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Sfield'),
        ),
    ]
