# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 10:00
from __future__ import unicode_literals

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=course.fields.ThumbnailImageField(default=3, upload_to='course/%Y/%m'),
            preserve_default=False,
        ),
    ]
