# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='repetition',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
