# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180711_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecturer.Lecturer'),
        ),
    ]
