# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_gender'),
        ('course', '0004_auto_20180908_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='accounts.Profile'),
        ),
    ]
