# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-26 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lfield',
            options={'ordering': ['lnumber']},
        ),
        migrations.AlterModelOptions(
            name='sfield',
            options={'ordering': ['snumber']},
        ),
    ]
