# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-28 17:09
from __future__ import unicode_literals

import course.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0004_auto_20181016_1448'),
        ('course', '0010_auto_20181016_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', course.fields.ThumbnailImageField(upload_to='course/%Y/%m')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecturer.Lecturer')),
            ],
            options={
                'ordering': ['course'],
            },
        ),
    ]
