# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 05:07
from __future__ import unicode_literals

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image2',
            field=course.fields.ThumbnailImageField(default=2, upload_to='course/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='image3',
            field=course.fields.ThumbnailImageField(default=2, upload_to='course/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='image4',
            field=course.fields.ThumbnailImageField(default=2, upload_to='course/%Y/%m'),
            preserve_default=False,
        ),
    ]
