# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='제목')),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일자')),
                ('modifydate', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자')),
                ('details', models.TextField(verbose_name='내용')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
