# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50, verbose_name='은행명')),
                ('account', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('career', models.TextField(verbose_name='경력사항')),
                ('certification', models.TextField(verbose_name='자격증')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'ordering': ['account'],
            },
        ),
    ]
