# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-11 09:08
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='idphoto',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='lecturer/post/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='profilephoto',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='lecturer/post/%Y/%m/%d'),
        ),
    ]
