# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-08 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_auto_20180711_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['name']},
        ),
    ]
