# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-16 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturer', '0003_auto_20180908_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='idphoto',
            field=imagekit.models.fields.ProcessedImageField(upload_to='lecturer/post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='profilephoto',
            field=imagekit.models.fields.ProcessedImageField(upload_to='lecturer/post/%Y/%m/%d'),
        ),
    ]
