# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycost', models.IntegerField(default=0, verbose_name='결제가격')),
                ('paydate', models.DateField(null=True)),
                ('enroldate', models.DateField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'ordering': ['paycost'],
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnumber', models.IntegerField(verbose_name='결제번호')),
                ('paymethod', models.CharField(max_length=50, verbose_name='결제방법')),
            ],
            options={
                'ordering': ['paymethod'],
            },
        ),
        migrations.AddField(
            model_name='enrol',
            name='paymethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrol.Pay'),
        ),
        migrations.AddField(
            model_name='enrol',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
